### ISSUE TITLE
Failure to build Calculator App with XCode 8.3 and Gcc Version 8.1.0 on OSX High Sierra

### ISSUE THREAD

**Issue by VincentToups** [part-cw/lambdanative#200]
```
=> compiling scheme payload..
    /tmp/lambdanative/modules/config/config.scm ..
    /tmp/lambdanative/modules/ln_core/ln_core.scm ..
 gcc  -DMACOSX -m64   -D___SINGLE_HOST -D___LIBRARY -D___PRIMAL -DSTANDALONE -c -o /Users/vincenttoups/Library/Caches/lambdanative/macosx/build/2268890858.o /Users/vincenttoups/Library/Caches/lambdanative/macosx/build/2268890858.c -I/Users/vincenttoups/Library/Caches/lambdanative/macosx/include -I/Users/vincenttoups/Library/Caches/lambdanative/macosx/include/freetype2 -I/tmp/lambdanative/modules/ln_core
In file included from /System/Library/Frameworks/Security.framework/Headers/AuthSession.h:32,
                 from /System/Library/Frameworks/Security.framework/Headers/Security.h:43,
                 from /System/Library/Frameworks/CoreServices.framework/Frameworks/OSServices.framework/Headers/CSIdentity.h:43,
                 from /System/Library/Frameworks/CoreServices.framework/Frameworks/OSServices.framework/Headers/OSServices.h:27,
                 from /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Headers/IconsCore.h:23,
                 from /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Headers/LaunchServices.h:22,
                 from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:39,
                 from /System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:23,
                 from /Users/vincenttoups/Library/Caches/lambdanative/macosx/build/2268890858.c:6742:
/System/Library/Frameworks/Security.framework/Headers/Authorization.h:193:7: error: variably modified 'bytes' at file scope
  char bytes[kAuthorizationExternalFormLength];
       ^~~~~
In file included from /System/Library/Frameworks/CoreGraphics.framework/Headers/CGContext.h:21,
                 from /System/Library/Frameworks/CoreGraphics.framework/Headers/CGBitmapContext.h:9,
                 from /System/Library/Frameworks/CoreGraphics.framework/Headers/CoreGraphics.h:11,
                 from /System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:35,
                 from /Users/vincenttoups/Library/Caches/lambdanative/macosx/build/2268890858.c:6742:
/System/Library/Frameworks/CoreGraphics.framework/Headers/CGPath.h:391:15: error: expected identifier or '(' before '^' token
 typedef void (^CGPathApplyBlock)(const CGPathElement * element);
               ^
/System/Library/Frameworks/CoreGraphics.framework/Headers/CGPath.h:393:53: error: unknown type name 'CGPathApplyBlock'
 CG_EXTERN void CGPathApplyWithBlock(CGPathRef path, CGPathApplyBlock CF_NOESCAPE block)
                                                     ^~~~~~~~~~~~~~~~
ERROR: failed on file /Users/vincenttoups/Library/Caches/lambdanative/macosx/build/2268890858.o
BUILD FAILED - configure with verbose option for more information
```

This is the latest commit on master. This is a fresh checkout of lambdanative and I've executed both `make scrub` and `make clean`. 

All I can think of is that I've manually downgraded XCode and perhaps there are some stale files somewhere?

**Comment by VincentToups** [comment]
The first thing to try is probably nailing down a specific version of GCC. At present I've installed a few versions of GCC with homebrew and symlinked them to /usr/local/bin/gcc . I get similar sorts of issues with GCC 4.9, though with the system Font rendering library, I believe.

**Comment by VincentToups** [comment]
With GCC5 I get what I believe is the same as the GCC4.9 error:

``` => compiling scheme payload..
    /tmp/lambdanative/modules/config/config.scm ..
    /tmp/lambdanative/modules/ln_core/ln_core.scm ..
 gcc  -DMACOSX -m64   -D___SINGLE_HOST -D___LIBRARY -D___PRIMAL -DSTANDALONE -c -o /Users/vincenttoups/Library/Caches/lambdanative/macosx/build/2268890858.o /Users/vincenttoups/Library/Caches/lambdanative/macosx/build/2268890858.c -I/Users/vincenttoups/Library/Caches/lambdanative/macosx/include -I/Users/vincenttoups/Library/Caches/lambdanative/macosx/include/freetype2 -I/tmp/lambdanative/modules/ln_core
In file included from /System/Library/Frameworks/Security.framework/Headers/AuthSession.h:32:0,
                 from /System/Library/Frameworks/Security.framework/Headers/Security.h:43,
                 from /System/Library/Frameworks/CoreServices.framework/Frameworks/OSServices.framework/Headers/CSIdentity.h:43,
                 from /System/Library/Frameworks/CoreServices.framework/Frameworks/OSServices.framework/Headers/OSServices.h:27,
                 from /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Headers/IconsCore.h:23,
                 from /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Headers/LaunchServices.h:22,
                 from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:39,
                 from /System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:23,
                 from /Users/vincenttoups/Library/Caches/lambdanative/macosx/build/2268890858.c:6742:
/System/Library/Frameworks/Security.framework/Headers/Authorization.h:193:7: error: variably modified 'bytes' at file scope
  char bytes[kAuthorizationExternalFormLength];
       ^
In file included from /usr/include/Availability.h:206:0,
                 from /usr/include/wchar.h:72,
                 from /Users/vincenttoups/Library/Caches/lambdanative/macosx/include/gambit.h:766,
                 from /Users/vincenttoups/Library/Caches/lambdanative/macosx/build/2268890858.c:923:
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Headers/LSInfoDeprecated.h:1244:34: error: expected ',' or '}' before '__attribute__'
   kLSHandlerOptionsDefault       __OSX_AVAILABLE_BUT_DEPRECATED_MSG(__MAC_10_4, __MAC_10_11, __IPHONE_4_0, __IPHONE_9_0, "Creator codes are deprecated on OS X.") = 0,
                                  ^
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Headers/LSOpenDeprecated.h:29:33: error: expected ',' or '}' before '__attribute__'
   kLSLaunchInhibitBGOnly        __OSX_AVAILABLE_BUT_DEPRECATED_MSG(__MAC_10_0, __MAC_10_12, __IPHONE_NA, __IPHONE_NA, "This option does nothing.") = 0x00000080, /* Does nothing.*/
                                 ^
In file included from /System/Library/Frameworks/CoreGraphics.framework/Headers/CGContext.h:18:0,
                 from /System/Library/Frameworks/CoreGraphics.framework/Headers/CGBitmapContext.h:9,
                 from /System/Library/Frameworks/CoreGraphics.framework/Headers/CoreGraphics.h:11,
                 from /System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:35,
                 from /Users/vincenttoups/Library/Caches/lambdanative/macosx/build/2268890858.c:6742:
/System/Library/Frameworks/CoreGraphics.framework/Headers/CGFont.h:53:40: error: initializer element is not constant
 static const CGFontIndex kCGGlyphMax = kCGFontIndexMax;
                                        ^
In file included from /System/Library/Frameworks/CoreGraphics.framework/Headers/CGContext.h:21:0,
                 from /System/Library/Frameworks/CoreGraphics.framework/Headers/CGBitmapContext.h:9,
                 from /System/Library/Frameworks/CoreGraphics.framework/Headers/CoreGraphics.h:11,
                 from /System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:35,
                 from /Users/vincenttoups/Library/Caches/lambdanative/macosx/build/2268890858.c:6742:
/System/Library/Frameworks/CoreGraphics.framework/Headers/CGPath.h:391:15: error: expected identifier or '(' before '^' token
 typedef void (^CGPathApplyBlock)(const CGPathElement * element);
               ^
/System/Library/Frameworks/CoreGraphics.framework/Headers/CGPath.h:393:53: error: unknown type name 'CGPathApplyBlock'
 CG_EXTERN void CGPathApplyWithBlock(CGPathRef path, CGPathApplyBlock CF_NOESCAPE block)
                                                     ^
ERROR: failed on file /Users/vincenttoups/Library/Caches/lambdanative/macosx/build/2268890858.o
BUILD FAILED - configure with verbose option for more information
```

**Comment by VincentToups** [comment]
I had this issue with a previous install of OSX before and the solution was to eventually move to a totally clean system (factory new) and install everything there. I'd like to avoid that, if possible.

**Comment by mgorges** [comment]
Okay so I have a similar setup, if not slightly newer Xcode: Using Apple LLVM version 9.1.0 (clang-902.0.39.2), as reported by `gcc -v` and Xcode 9.4.1, as reported by `xcodebuild -version` on MacOS 10.13.5, as reported by `sw_vers -productVersion`. 

Just to confirm, the main difference is that you'd like to use GCC, not Clang as the compiler? There are some potentially related issues to this: [Rstudio: Issue 132](https://github.com/rstudio/httpuv/issues/132), [MITK: Issue 24259](https://phabricator.mitk.org/T24259) that sound similar.

**Comment by VincentToups** [comment]
I was under the impression that gcc was a requirement? I've just unlinked
the gcc symlink and built the osx version with clang - successfully!

However, I am getting

```
  CHOST=arm-apple-darwin17.6.0
PKG_CONFIG_PATH=/Users/vincenttoups/Library/Caches/lambdanative/ios/armv7/lib/pkgconfig
PATH="/Users/vincenttoups/Library/Caches/lambdanative/ios/armv7/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands"
LDFLAGS=-L/Users/vincenttoups/Library/Caches/lambdanative/ios/armv7/lib
LD_LIBRARY_PATH=/Users/vincenttoups/Library/Caches/lambdanative/ios/armv7/lib
CPPFLAGS=-I/Users/vincenttoups/Library/Caches/lambdanative/ios/armv7/include
CC="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-arch armv7 -g -O0 -isysroot
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk
-DIOS -DIPHONE -miphoneos-version-min=5.1.1 -fPIC -fsigned-char
-fomit-frame-pointer
-I/Users/vincenttoups/Library/Caches/lambdanative/ios/armv7/include
-L/Users/vincenttoups/Library/Caches/lambdanative/ios/armv7/lib"
AR="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar"
RANLIB="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib"
NM="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/nm"
LD="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld"
AS="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/as"
CPP=""   OBJCOPY=""
STRIP="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip"
GPROF=""   READELF=""   OBJDUMP=""   ./configure
--prefix=/Users/vincenttoups/Library/Caches/lambdanative/ios/armv7
--host=arm
checking build system type... x86_64-apple-darwin17.6.0
checking host system type... arm-unknown-none
checking target system type... arm-unknown-none
checking for arm-gcc...
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-arch armv7 -g -O0 -isysroot
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk
-DIOS -DIPHONE -miphoneos-version-min=5.1.1 -fPIC -fsigned-char
-fomit-frame-pointer
-I/Users/vincenttoups/Library/Caches/lambdanative/ios/armv7/include
-L/Users/vincenttoups/Library/Caches/lambdanative/ios/armv7/lib
checking whether the C compiler works... no
configure: error: in
`/Users/vincenttoups/.lambdanative/tmp_install/gambc-v4_7_9':
configure: error: C compiler cannot create executables

```

When I try to build the ios version?

**Comment by mgorges** [comment]
Please check if your version of Xcode has a minimum supported version of 6.0 (not 5.1.1) - that might be required to build with armv7?

**Comment by VincentToups** [comment]
Xcode is 8.3.

**Comment by mgorges** [comment]
I am talking about the minimum version of iOS support, which you seem to have set at 5.1.1 not 6.0

**Comment by VincentToups** [comment]
There we go!  I now seem to be building the iOS version, but I'm having some trouble signing the release build, though as far as I can tell, my PROFILE has the right information (it matches what shows up in the distribution provision information in my test project in XCode). 

Unfortunately, I can't actually deploy the test project because XCode tells me that it doesn't support my iPhone iOS version. Can I safely upgrade XCode to the latest version? Or is there some other magical incantation I can use to get lambdanative to find my provisioning profile?

```=== BUILD TARGET CorpseWizard OF PROJECT CorpseWizard WITH CONFIGURATION Release ===
Check dependencies
No iOS profile matching '*********/Distribution' found:  Xcode couldn't find a profile matching 'TG3C9XX7TZ/Distribution'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the General tab of the target editor.
Code signing is required for product type 'Application' in SDK 'iOS 10.3'
** BUILD FAILED **
The following build commands failed:
	Check dependencies
(1 failure)
ERROR: failed with exit code 65
BUILD FAILED - configure with verbose option for more information```

Profile looks like this:

```
# iOS release (SYS_IOSRELCERT) and development (SYS_IOSDEVCERT) names:
SYS_IOSRELCERT="iPhone Distribution: Vincent Toups (*********)"
SYS_IOSDEVCERT="iPhone Developer: Vincent Toups (*********)"
```

Where obviously the asterisks are replaced by the identifier for my profile and match in the two snippets.

**Comment by mgorges** [comment]
The "appropriate" provisioning profile is automatically identified by the codesigning piece, during packaging. There might be a way to override that but I currently don't know how, so we rely on this working. Do you see both the certificates and private keys in your login keychain?

You don't actually sign the release build - Apple does. Next, I believe we nowadays only use the content in team id (in the bracket) for anything and the rest of those variables get replaced in the `make.sh`. Finally, I currently use Xcode 9.4.1, so that is the latest version we tested.

**Comment by mgorges** [comment]
Maybe also look at [Issue 159](https://github.com/part-cw/lambdanative/issues/159)

**Comment by VincentToups** [comment]
Unfortunately, I still get 

```
make -f /Users/vincenttoups/.lambdanative/tmp.3oDi38/CMakeScripts/ReRunCMake.make
make[2]: `/Users/vincenttoups/.lambdanative/tmp.3oDi38/CMakeFiles/cmake.check_cache' is up to date.
=== BUILD TARGET CorpseWizard OF PROJECT CorpseWizard WITH CONFIGURATION Release ===
Check dependencies
Code Signing Error: No profile for team '*********' matching 'Distribution' found:  Xcode couldn't find any provisioning profiles matching '*********/Distribution'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the General tab of the target editor.
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.4'
** BUILD FAILED **
The following build commands failed:
	Check dependencies
(1 failure)
ERROR: failed with exit code 65
BUILD FAILED - configure with verbose option for more information
make: *** [all] Error 1
capitulation:lambdanative vincenttoups$ 


```

**Comment by VincentToups** [comment]
Where is the code that is attempting the signing, I'd like to take a poke at it.

**Comment by mgorges** [comment]
Two potential places as it kind-of happens twice in our current setup: [targets/ios/build-binary#L127](https://github.com/part-cw/lambdanative/blob/master/targets/ios/build-binary#L127) and [targets/ios/package#L68](https://github.com/part-cw/lambdanative/blob/master/targets/ios/package#L68)

**Comment by VincentToups** [comment]
Unfortunately, I'm still struggling with this - I can build an app with the appropriate certificates and profiles in XCode but my lambdanative build can never find the certificate associated with Distribution.

Does lambdanative generate an xcode project somewhere that I can open and fiddle with manaully?

**Comment by VincentToups** [comment]
Also, would I need to make clean or scrub between trying different PROFILE's or should that not make a difference?

**Comment by mgorges** [comment]
The signing is something that happens in the temporary files so I don't expect that cleaning/scrubbing your cache will make any difference. 

_LambdaNative_ does not make an Xcode project per se but you get the pieces that are run through `cmake`, `codesign` etc. building process if you were to comment [targets/ios/build-binary#L167](https://github.com/part-cw/lambdanative/blob/master/targets/ios/build-binary#L167), or add an return 0 before it, so they don't get clean up at the end.

**Comment by VincentToups** [comment]
It seems like the codesigning error is happening before build-binary. In `Check Dependencies`. I've inserted echo's before each codesign invocation in `build-binary` and I never reach either (unless somehow the scripts silence echo). 

Where can I see the code run in `Check Dependencies`? I've grepped around without luck.

**Comment by mgorges** [comment]
Not sure about the `Check Dependencies` location, that output is from the build process itself. - There are potentially more code-sign related things in [targets/ios/package#L68](https://github.com/part-cw/lambdanative/blob/master/targets/ios/package#L68)

**Comment by karliwalti** [comment]
I'm not sure if this info helps for the discussion, but the only way for us to have the  iOS code signing work is to create a dummy app project in Xcode with the same name as the lambdanative target app. Generate a provisioning file with Xcode  and download it as described here: [generate-a-provisioning-profile-with-xcode](https://ioscodesigning.com/generating-code-signing-files/#generate-a-provisioning-profile-with-xcode)
Once this is completed, then also the LN build process stops throwing signing errors.

**Comment by VincentToups** [comment]
Can you elaborate on this process?

I've created a dummy app and built and archived it, but XCode doesn't
appear to upload the provisioning profile it creates anywhere. Even after
archiving (and signing) my dummy app, my apple developer account contains
no provisioning profiles to download.

-V

**Comment by karliwalti** [comment]
You can't do this? 


> Select Xcode > Preferences from the navigation bar.
At the top of the window select Accounts.
Select your Apple ID and your team, then select Download Manual Profiles.
Go to ~/Library/MobileDevice/Provisioning Profiles/ and your profiles should be there.

**Comment by karliwalti** [comment]
I seem to only be able to sign for the developer version of my apps, not the distribution. The trick with dummy app in Xcode does not work either. Same error message as reported above.

**Comment by VincentToups** [comment]
Yeah. I've tried just about everything except starting with a completely
clean install of OSX.

**Comment by karliwalti** [comment]
Maybe something like fastlane could help here

**Comment by VincentToups** [comment]
Yeah, fastlane seems to require an xcode project to run in and I'm not sure
how it works. I've considered just building the debug version andr esigning
it manually.

**Comment by mgorges** [comment]
I am still puzzled by the problem and doubt that a clean install of MacOS would fix this for you either. There is something else about your setup that isn't quite right and causes the `LambdaNative` build process to miss your provisioning profile. This is exceptionally hard to debug remotely as I don't have the full picture but one thing for you to consider might be to hardcode the certificates you wish to sign with, instead of letting the system try and identify the correct one for you?

**Comment by karliwalti** [comment]
Since the error  is like 

> Code Signing Error: No profile for team 'XXXXXXX' matching 'Distribution' found

Apple seems to always use the name for team, not the certificate code, so maybe the wrong term is provided to the search?

**Comment by mgorges** [comment]
@karliwalti, I the name gets stripped away in [make.sh#L825](https://github.com/part-cw/lambdanative/blob/master/make.sh#L825) and [make.sh#L819](https://github.com/part-cw/lambdanative/blob/master/make.sh#L819) replaces provisioning profile as well?

**Comment by karliwalti** [comment]
Could you share you current system setup, maybe we can update to there and compare?

**Comment by mgorges** [comment]
Sorry, don't know how to refer to earlier entries in this thread; my first response (item 5) has Xcode version `9.4.1`, this is on MacOS `10.13.6`. My minimum IOS version is set to `IOSVERSION=6` and the entries in my `PROFILE` are pretty much like in the template, something like this:

    SYS_PROFILE="PART BC Children's"
    SYS_ORGTLD="org"
    SYS_ORGSLD="ecemgroup"
    SYS_IOSRELCERT="iPhone Distribution: PART BC Children's (A...Q)"
    SYS_IOSDEVCERT="iPhone Developer: PART BC Children's (G...7)"

**Comment by karliwalti** [comment]
thx. so far on same level, without solving the issue.  Which method are you using for adding a provisioning profile?

**Comment by karliwalti** [comment]
I tried to manually sign. for this I set 

 `set_target_properties(${NAME} PROPERTIES XCODE_ATTRIBUTE_PROVISIONING_STYLE "Manual")`
in CMakeLists.txt.in  and hardcode the
`  set_target_properties(${NAME} PROPERTIES XCODE_ATTRIBUTE_PROVISIONING_PROFILE_SPECIFIER "@SYS_IOSPROVISIONING@") `
to the name of my locally saved profile

It moves me a step further, but now there is no app store profile to be discovered. Building for "package" instead "app-store" seems to be not supported anymore



> making ios ipa..
cp: /Users/wkarlen/Library/Caches/lambdanative/build/lncalculator/export/lncalculator.ipa: No such file or directory
xcodebuild -exportArchive -archivePath /Users/wkarlen/Library/Caches/lambdanative/ios/armv7/lncalculator-1.0.xcarchive -exportPath /Users/wkarlen/Library/Caches/lambdanative/build/lncalculator/export -exportOptionsPlist /Users/wkarlen/Library/Caches/lambdanative/build/lncalculator/exportOptions.plist
2018-08-02 16:01:14.010 xcodebuild[52750:897420] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/0f/_9jy8j8n14g9_cggjh4f0xcm0000gr/T/lncalculator_2018-08-02_16-01-14.009.xcdistributionlogs'.
2018-08-02 16:01:14.344 xcodebuild[52750:897420] [MT] IDEDistribution: Step failed: <IDEDistributionSigningAssetsStep: 0x7fea11e58040>: Error Domain=IDEDistributionSigningAssetStepErrorDomain Code=0 "Locating signing assets failed." UserInfo={NSLocalizedDescription=Locating signing assets failed., IDEDistributionSigningAssetStepUnderlyingErrors=(
    "Error Domain=IDEProfileLocatorErrorDomain Code=4 \"No \"iOS App Store\" profiles for team 'XXXXXXX' matching 'Distribution' are installed.\" UserInfo={NSLocalizedDescription=No \"iOS App Store\" profiles for team 'XXXXX' matching 'Distribution' are installed., NSLocalizedRecoverySuggestion=Install a profile (by dragging and dropping it onto Xcode's dock item) or specify a different profile in your Export Options property list.}"
)}
error: exportArchive: No "iOS App Store" profiles for team 'XXXXXX' matching 'Distribution' are installed.
Error Domain=IDEProfileLocatorErrorDomain Code=4 "No "iOS App Store" profiles for team 'XXXXXX' matching 'Distribution' are installed." UserInfo={NSLocalizedDescription=No "iOS App Store" profiles for team 'XXXXXX' matching 'Distribution' are installed., NSLocalizedRecoverySuggestion=Install a profile (by dragging and dropping it onto Xcode's dock item) or specify a different profile in your Export Options property list.}
** EXPORT FAILED **
ERROR: failed on file /Users/wkarlen/Library/Caches/lambdanative/packages/lncalculator-1.0-ios.ipa
BUILD FAILED - configure with verbose option for more information
make: *** [all] Error 1

**Comment by mgorges** [comment]
The signing step should already have failed for you by the time you reach the `making iOS ipa`step? If you go back in the log, what do you get for the following piece?

    CodeSign /Users/mgorges/Library/Developer/Xcode/DerivedData/RRate-afzqkdahhptpuaanbebztramuwjm/ArchiveIntermediates/RRate/InstallationBuildProductsLocation/Applications/RRate.app
    cd /Users/mgorges/.lambdanative/tmp.bR8RS9
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:/Applications/Wireshark.app/Contents/MacOS"
    
    Signing Identity:     "iPhone Distribution: PART BC Children's (A...Q)"
    Provisioning Profile: "Distribution"
                      (be8baca...b7bc1c)

    /usr/bin/codesign --force --sign 81A84157D3B1A60BC844E17E16D91C1ECA4D7D4C --entitlements /Users/mgorges/Library/Developer/Xcode/DerivedData/RRate-afzqkdahhptpuaanbebztramuwjm/ArchiveI

**Comment by karliwalti** [comment]
how do I get this log?

**Comment by mgorges** [comment]
this is from the middle section of `./configure RRate ios release verbose; make`

**Comment by mgorges** [comment]
The be8baca...b7bc1c file is listed it I do `ls ~/Library/MobileDevice/Provisioning\ Profiles` and its properties are: 

    App ID Name: WindcardAppID
    App ID: KD...*
    Team: PART BC Children's (A...Q)
    Platform: iOS
    [...]

**Comment by karliwalti** [comment]
I see, verbose mode...

I get 

```
CodeSign /Users/wkarlen/Library/Developer/Xcode/DerivedData/lncalculator-fnjcbbglscfznodfqyrupcmewvdj/ArchiveIntermediates/lncalculator/InstallationBuildProductsLocation/Applications/lncalculator.app
    cd /Users/wkarlen/.lambdanative/tmp.or6W85
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    
Signing Identity:     "iPhone Distribution: Walter Karlen (Q...C)"
Provisioning Profile: "lncalculatorProvProRelease"
                      (6d41......ed07)

    /usr/bin/codesign --force --sign 4528DD2F76A69CFD04B1A09DF0DC4C47D2F41BD7 --entitlements /Users/wkarlen/Library/Developer/Xcode/DerivedData/lncalculator-fnjcbbglscfznodfqyrupcmewvdj/ArchiveIntermediates/lncalculator/IntermediateB
Validate /Users/wkarlen/Library/Developer/Xcode/DerivedData/lncalculator-fnjcbbglscfznodfqyrupcmewvdj/ArchiveIntermediates/lncalculator/InstallationBuildProductsLocation/Applications/lncalculator.app
    cd /Users/wkarlen/.lambdanative/tmp.or6W85
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    export PRODUCT_TYPE=com.apple.product-type.application
    builtin-validationUtility /Users/wkarlen/Library/Developer/Xcode/DerivedData/lncalculator-fnjcbbglscfznodfqyrupcmewvdj/ArchiveIntermediates/lncalculator/InstallationBuildProductsLocation/Applications/lncalculator.app

** ARCHIVE SUCCEEDED **
```

so that is successful, and I have zip files in the cache

I can add it to the Xcode application loader, it takes a while and then throws 

`ERROR ITMS-90529: "Invalid package. Applications built with sdk 9.0 or later must be packaged as proper IPA files."`

**Comment by mgorges** [comment]
The application loader only takes **IPA** files, not **ZIP** files. Also you changed `CMakeLists.txt.in`, but the stuff the exportArchive uses is set in [loaders/ios/exportOptions.plist.in](https://github.com/part-cw/lambdanative/blob/master/loaders/ios/exportOptions.plist.in), so you might have to change things there? Note that Line 8 gets changed from "development" to "app-store" by [targets/ios/package#L54](https://github.com/part-cw/lambdanative/blob/master/targets/ios/package#L54)

**Comment by karliwalti** [comment]
it actually does take zip (and embedded .app) files. 
I was modifying the make.sh file to change parameters.

And after all I have some success to report:
With manual signing things compile and export. following changes were done/may be  needed:

make.sh:
```
if [ "$SYS_MODE" = "release" ]; then
    SYS_IOSCERT=`echo $SYS_IOSRELCERT`
    SYS_IOSPROVISIONING="HARDCODED PROFILE NAME - WILDCARD WORKS"
  else
    SYS_IOSCERT="iPhone Developer"
  fi
  SYS_IOSTEAMID=`echo "$SYS_IOSRELCERT" | cut -f 2 -d "(" | cut -f 1 -d ")"`

```
using wildcard profile will avoid to change too frequently or better to add to configure?

exportOptions:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>teamID</key>
  <string>@SYS_IOSTEAMID@</string>
  <key>method</key>
  <string>development</string>
  <key>signingStyle</key>
  <string>manual</string>
  <key>uploadSymbols</key>
  <true/>
  <key>provisioningProfiles</key>
  <dict>
    <key>@SYS_ORGTLD@.@SYS_ORGSLD@.@SYS_LOCASEAPPNAME@</key>
    <string>@SYS_IOSPROVISIONING@</string>
  </dict>
</dict>
</plist>
```

**Comment by VincentToups** [comment]
Can you show us this as a patch (via git diff)?

**Comment by mgorges** [comment]
Okay maybe I misspoke about the IPA being required, but for the apps we currently have on the store Apple never approved the ZIP files but only the IPA ones as there must be a subtle difference in something packaged in there. 

The change you suggest to the make file, other than adding the provisioning profile label is interesting, as it reverts commit 581c655, which was made in an attempt to start working again with XCode8. I also think that your patch partially depends on some hardcoded changes you made to CMakeLists.txt.in which would also need to be included. -> Before I attempt to put those in I'd still like to see if there remains a way of automatically identifying the right provisioning profile (maybe it only works because ours is actually called "Distribution" in the [iOS Provisioning Profile - Apple Developer](https://developer.apple.com/account/ios/profile/) website.

**Comment by mgorges** [comment]
Digging into the `make.sh` more the change to "SYS_IOSCERT" is actually ignored, you can put anything there and it still works, so `SYS_IOSPROVISIONING` is the only piece you suggest adding there.

**Comment by mgorges** [comment]
@VincentToups - I think with his comment @karliwalti actually might have found the solution though. If you have a look (by pressing space) at the Provisioning Profile in `~/Library/MobileDevice/Provisioning\ Profiles` you'd like to use, what is its name? Here, my release one is saying "Distribution" on top, while the development on used if not using release mode, says: "iOS Team Provisioning Profile: *"

**Comment by mgorges** [comment]
There is probably a better way to do it but one way to extract these programatically is this: 

    cd "~/Library/MobileDevice/Provisioning\ Profiles"
    for file in `ls *.mobileprovision`; do 
      name=`security cms -D -i $file | grep -A1 "<key>Name</key>"| tail -n1 | sed -n 's:.*<string>\(.*\)</string>.*:\1:p'`
      echo $file "$name"
    done

**Comment by karliwalti** [comment]
@mgorges  just checked by renaming my wildcard provision profile to Distribution and it indeed works.  this was your lucky chance, because I believe there is no automatic signing for release, this is only available for development. Even in Xcode GUI version there is no automatic option for release

Finally I suggest following changes:

add to PROFILE:
`SYS_IOSMOBILEPROVISION="provision file id"`
change in make.sh:
````
SYS_IOSPROVISIONING=`echo $SYS_IOSMOBILEPROVISION`
````
and change string in loaders/ios/exportOptions.plist.in to
````
<key>provisioningProfiles</key>
  <dict>
    <key>@SYS_ORGTLD@.@SYS_ORGSLD@.@SYS_LOCASEAPPNAME@</key>
    <string>@SYS_IOSPROVISIONING@</string>
  </dict>

```

this will do. the manual building is default

**Comment by mgorges** [comment]
Thanks a lot @karliwalti for your help in sorting this out! I guess we never changed it from its old Xcode 5/6 name and thus this worked for us. 

Will see if I can automatically query the list of available profiles in the cache, select the release one, and then set it in the make.sh and otherwise will implement as you suggested.

**Comment by mgorges** [comment]
Should be fixed with 7155c9c

**Comment by karliwalti** [comment]
I think you forgot the change in loaders/ios/exportOptions.plist.in  Distribution was hardcoded there too

**Comment by mgorges** [comment]
I thought I fixed it in [loaders/ios/exportOptions.plist.in#L14](https://github.com/part-cw/lambdanative/blob/master/loaders/ios/exportOptions.plist.in#L14)?
